import cover_1 from "./assets/cover_1.jpg";
import cover_2 from "./assets/cover_2.jpg";
import { GenderOptions, ISong } from "./types";

export const genders: GenderOptions[] = ["Любой", "Мужской", "Женский"];

export const genres = [
  "Поп",
  "Поп-рок",
  "Танцевальная",
  "Хип-хоп/RnB/Trap",
  "Шансон",
];

export const moods = ["Веселое", "Грустное", "Свэг"];

export const songs: ISong[] = [
  {
    cover_url: cover_1,
    created_at: "some_date",
    duration: 209,
    id: 1,
    lyric: `Куплет 1 За окном до утра Говорили холода Говорили холода За мое все отдам В эти злые времена Все не стынет голова Ты просто 10 баллов Пробками до вокзала`,
    name: "Думала",
    price: "100 000₽",
    primary_genre: "Поп",
    moods: ["Грустное"],
    raiting: 3,
    sex: "Женский",
  },
  {
    cover_url: cover_2,
    created_at: "some_date",
    duration: 209,
    id: 2,
    lyric: "some text",
    name: "Футболка",
    price: "120 000₽",
    primary_genre: "Хип-хоп/RnB/Trap",
    moods: ["Свэг"],
    raiting: 2,
    sex: "Мужской",
  },
  {
    cover_url: cover_1,
    created_at: "some_date",
    duration: 209,
    id: 3,
    lyric: "some text",
    name: "Думала",
    price: "100 000₽",
    primary_genre: "Поп",
    moods: ["Грустное"],
    raiting: 3,
    sex: "Женский",
  },
  {
    cover_url: cover_2,
    created_at: "some_date",
    duration: 209,
    id: 4,
    lyric: "some text",
    name: "Футболка",
    price: "120 000₽",
    primary_genre: "Хип-хоп/RnB/Trap",
    moods: ["Свэг"],
    raiting: 2,
    sex: "Мужской",
  },
  {
    cover_url: cover_1,
    created_at: "some_date",
    duration: 209,
    id: 5,
    lyric: "some text",
    name: "Думала",
    price: "100 000₽",
    primary_genre: "Поп",
    moods: ["Грустное"],
    raiting: 3,
    sex: "Женский",
  },
  {
    cover_url: cover_2,
    created_at: "some_date",
    duration: 209,
    id: 6,
    lyric: "some text",
    name: "Футболка",
    price: "120 000₽",
    primary_genre: "Хип-хоп/RnB/Trap",
    moods: ["Свэг"],
    raiting: 2,
    sex: "Мужской",
  },
  {
    cover_url: cover_1,
    created_at: "some_date",
    duration: 209,
    id: 7,
    lyric: "some text",
    name: "Думала",
    price: "100 000₽",
    primary_genre: "Поп",
    moods: ["Грустное"],
    raiting: 3,
    sex: "Женский",
  },
  {
    cover_url: cover_2,
    created_at: "some_date",
    duration: 209,
    id: 8,
    lyric: "some text",
    name: "Футболка",
    price: "120 000₽",
    primary_genre: "Хип-хоп/RnB/Trap",
    moods: ["Свэг"],
    raiting: 2,
    sex: "Мужской",
  },
  {
    cover_url: cover_1,
    created_at: "some_date",
    duration: 209,
    id: 9,
    lyric: "some text",
    name: "Думала",
    price: "100 000₽",
    primary_genre: "Поп",
    moods: ["Грустное"],
    raiting: 3,
    sex: "Женский",
  },
  {
    cover_url: cover_2,
    created_at: "some_date",
    duration: 209,
    id: 10,
    lyric: "some text",
    name: "Футболка",
    price: "120 000₽",
    primary_genre: "Хип-хоп/RnB/Trap",
    moods: ["Свэг"],
    raiting: 2,
    sex: "Мужской",
  },
];
